package org.planit.graph;

import java.util.logging.Logger;

import org.planit.utils.exceptions.PlanItException;
import org.planit.utils.graph.DirectedEdge;
import org.planit.utils.graph.DirectedVertex;
import org.planit.utils.graph.EdgeSegment;
import org.planit.utils.graph.EdgeSegments;
import org.planit.utils.graph.Edges;
import org.planit.utils.graph.Vertex;
import org.planit.utils.graph.Vertices;
import org.planit.utils.id.IdGenerator;
import org.planit.utils.id.IdGroupingToken;

/**
 * Create network entities with direction for a physical network simulation model
 * 
 * @author markr
 *
 */
public class DirectedGraphBuilderImpl implements DirectedGraphBuilder<DirectedVertex, DirectedEdge, EdgeSegment> {

  @SuppressWarnings("unused")
  private static final Logger LOGGER = Logger.getLogger(DirectedGraphBuilderImpl.class.getCanonicalName());

  /** use graph builder impl for overlapping functionality */
  private final GraphBuilderImpl graphBuilder = new GraphBuilderImpl();

  /**
   * {@inheritDoc}
   */
  @Override
  public DirectedVertex createVertex() {
    return new DirectedVertexImpl(graphBuilder.getIdGroupingToken());
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public DirectedEdge createEdge(Vertex vertexA, Vertex vertexB, final double lengthKm) throws PlanItException {
    if (vertexA instanceof DirectedVertex && vertexB instanceof DirectedVertex) {
      return new DirectedEdgeImpl(graphBuilder.getIdGroupingToken(), (DirectedVertex) vertexA, (DirectedVertex) vertexB, lengthKm);
    }
    throw new PlanItException("unable to create directed edge since provides vertices are not directed");
  }

  @Override
  public DirectedEdge copyEdge(DirectedEdge edgeToCopy) {
    // TODO Auto-generated method stub
    return null;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public EdgeSegment createEdgeSegment(DirectedEdge parentEdge, boolean directionAB) throws PlanItException {
    return new EdgeSegmentImpl(graphBuilder.getIdGroupingToken(), parentEdge, directionAB);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void setIdGroupingToken(IdGroupingToken groupToken) {
    graphBuilder.setIdGroupingToken(groupToken);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public IdGroupingToken getIdGroupingToken() {
    return graphBuilder.getIdGroupingToken();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void recreateIds(Edges<? extends DirectedEdge> edges) {
    graphBuilder.recreateIds(edges);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void recreateIds(Vertices<? extends DirectedVertex> vertices) {
    graphBuilder.recreateIds(vertices);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public void recreateIds(EdgeSegments<? extends DirectedEdge, ? extends EdgeSegment> edgeSegments) {
    if (edgeSegments instanceof EdgeSegmentsImpl<?, ?>) {
      /* remove gaps by simply resetting and recreating all edge segment ids */
      IdGenerator.reset(getIdGroupingToken(), EdgeSegment.class);

      for (EdgeSegment edgeSegment : edgeSegments) {
        if (edgeSegment instanceof EdgeSegmentImpl) {
          ((EdgeSegmentImpl) edgeSegment).setId(EdgeSegmentImpl.generateEdgeSegmentId(getIdGroupingToken()));
        } else {
          LOGGER.severe(String.format("attempting to reset id on edgse segment (%s) that is not compatible with the edge segment implementation generated by this builder, ignored",
              edgeSegment.getClass().getCanonicalName()));
        }
      }

      ((EdgeSegmentsImpl<?, ?>) edgeSegments).updateIdMapping();
    } else {
      LOGGER.severe("expected the Edge segment implementation to be compatible with graph builder, this is not the case: unable to correctly remove subnetwork and update ids");
    }
  }

}
